-- AlterTable
ALTER TABLE "Import" ADD COLUMN     "failedRows" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "processedRows" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalRows" INTEGER NOT NULL DEFAULT 0;
